export const users = [
  {
    rank: 1,
    name: "김영희",
    username: "@101동",
    title: "🌟에코 히어로",
    avatar: "",
    stats: { total: 12000, monthly: 1500 },
    bgColor: "bg-yellow-100",
    crownColor: "text-yellow-400",
    weeklyPoints: 1500,
    totalPoints: 12000,
  },
  {
    rank: 2,
    name: "김철수",
    username: "@105동",
    title: "🌍지구 지키미",
    avatar: "",
    stats: { total: 8000, monthly: 1000 },
    bgColor: "bg-gray-200",
    crownColor: "text-gray-400",
    weeklyPoints: 1300,
    totalPoints: 8000,
  },
  {
    rank: 3,
    name: "홍길동",
    username: "@103동",
    title: "🗑 분리배출 견습생",
    avatar: "",
    stats: { total: 7500, monthly: 1500 },
    bgColor: "bg-orange-100",
    crownColor: "text-orange-400",
    weeklyPoints: 1100,
    totalPoints: 2300,
  },
  {
    rank: 4,
    name: "이순신",
    username: "@102동",
    title: "🌍지구 지키미",
    avatar: "",
    weeklyPoints: 900,
    totalPoints: 7000,
  },
  {
    rank: 5,
    name: "유관순",
    username: "@106동",
    title: "🌍지구 지키미",
    avatar: "",
    weeklyPoints: 850,
    totalPoints: 6800,
  },
  {
    rank: 6,
    name: "안중근",
    username: "@107동",
    title: "🌍지구 지키미",
    avatar: "",
    weeklyPoints: 800,
    totalPoints: 6700,
  },
  {
    rank: 7,
    name: "장영실",
    username: "@108동",
    title: "🌍지구 지키미",
    avatar: "",
    weeklyPoints: 750,
    totalPoints: 6600,
  },
  {
    rank: 8,
    name: "세종대왕",
    username: "@109동",
    title: "🌍지구 지키미",
    avatar: "",
    weeklyPoints: 700,
    totalPoints: 6500,
  },
  {
    rank: 9,
    name: "신사임당",
    username: "@110동",
    title: "🌍지구 지키미",
    avatar: "",
    weeklyPoints: 650,
    totalPoints: 6400,
  },
  {
    rank: 10,
    name: "율곡이이",
    username: "@111동",
    title: "🌍지구 지키미",
    avatar: "",
    weeklyPoints: 600,
    totalPoints: 6300,
  },
];
