export const users = [
  {
    rank: 1,
    name: "김영희",
    title: "🌟에코 히어로",
    bgColor: "bg-yellow-100",
    crownColor: "text-yellow-400",
    monthlyPoints: 1500,
    totalPoints: 12000,
  },
  {
    rank: 2,
    name: "김철수",
    title: "🌍지구 지키미",
    bgColor: "bg-gray-200",
    crownColor: "text-gray-400",
    monthlyPoints: 1300,
    totalPoints: 8000,
  },
  {
    rank: 3,
    name: "홍길동",
    title: "🗑 분리배출 견습생",
    bgColor: "bg-orange-100",
    crownColor: "text-orange-400",
    monthlyPoints: 1100,
    totalPoints: 2300,
  },
  {
    rank: 4,
    name: "이순신",
    title: "🌍지구 지키미",
    monthlyPoints: 900,
    totalPoints: 7000,
  },
  {
    rank: 5,
    name: "유관순",
    title: "🌍지구 지키미",
    monthlyPoints: 850,
    totalPoints: 6800,
  },
  {
    rank: 6,
    name: "안중근",
    title: "🌍지구 지키미",
    monthlyPoints: 800,
    totalPoints: 6700,
  },
  {
    rank: 7,
    name: "장영실",
    title: "🌍지구 지키미",
    monthlyPoints: 750,
    totalPoints: 6600,
  },
  {
    rank: 8,
    name: "세종대왕",
    title: "🌍지구 지키미",
    monthlyPoints: 700,
    totalPoints: 6500,
  },
  {
    rank: 9,
    name: "신사임당",
    title: "🌍지구 지키미",
    monthlyPoints: 650,
    totalPoints: 6400,
  },
  {
    rank: 10,
    name: "율곡이이",
    title: "🌍지구 지키미",
    monthlyPoints: 600,
    totalPoints: 6300,
  },
]
